# Brunftzeit für Termhirsche

Dieses Jupyter-Notebook enthält den Quelltext für Kapitel 6 »Brunftzeit für Termhirsche« im Buch [Python für Ingenieure für Dummies](https://python-fuer-ingenieure.de/).


### Einführungsbeispiel

In [1]:
# sorgt dafür, dass, wenn die letzte Zeile eine Zuweisung ist, deren Ergebnis auch ausgegeben wird
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

`begin golden_ratio`

In [2]:
import sympy as sp
Phi, a, b = sp.symbols('Phi, a, b')
# Gleichung a/b = (a + b)/a definieren
# In SymPy sind wird die rechte Seite immer als = 0 angenommen
# Wir müssen also in diese Form umstellen
ab_eq = a/b - (a+b)/a

a/b - (a + b)/a

In [3]:
ab_eq = ab_eq.expand()  # Summanden alle einzeln

a/b - 1 - b/a

In [4]:
# Ersetze a/b durch Phi
phi_eq = ab_eq.subs([(a/b, Phi), (b/a, 1/Phi)])

Phi - 1 - 1/Phi

In [5]:
# Löse nach Phi
symb_solutions = sp.solve(phi_eq, Phi)

[1/2 - sqrt(5)/2, 1/2 + sqrt(5)/2]

In [6]:
num_solutions = [sol.evalf() for sol in symb_solutions]

[-0.618033988749895, 1.61803398874989]

`end golden_ratio`

`begin symbol_defs_1`

In [7]:
x = sp.Symbol('x')

x

In [8]:
x, y = sp.symbols('x, y')
x

x

In [9]:
y

y

In [10]:
august_der_starke = sp.symbols('z')

z

`end symbol_defs_1`

`begin symbol_defs_2`

In [11]:
x1 = sp.Symbol('x1')

x1

In [12]:
xa = sp.Symbol('x_a')

x_a

In [13]:
xd = sp.Symbol('\\dot x')

\dot x

In [14]:
xb = sp.Symbol('\\bar x')

\bar x

In [15]:
om = sp.Symbol('Omega')

Omega

In [16]:
ddphi1 = sp.Symbol('\\ddot{\\varphi}_1')

\ddot{\varphi}_1

`end`

`begin expr_1`

In [17]:
x = sp.Symbol('x')
term1 = 4 + 2*x/3 + 5*x**2 - 7/x

5*x**2 + 2*x/3 + 4 - 7/x

`end`

`begin expr_trap`

In [18]:
x = sp.Symbol('x')
term1 = 4 + 2/3*x + 5*x**2 - 7/x

5*x**2 + 0.666666666666667*x + 4 - 7/x

`end`

`begin trap_explanation`

In [19]:
2/3

0.6666666666666666

In [20]:
type(2/3)

float

In [21]:
sp.S(2)/sp.S(3)

2/3

In [22]:
type(sp.S(2)/sp.S(3))

sympy.core.numbers.Rational

In [23]:
sp.S(2)/sp.S(3)*x

2*x/3

`end`

`begin expr_2`

In [24]:
x = sp.Symbol('x')
sp.sin(x)*sp.exp(2*x)

exp(2*x)*sin(x)

`end`

In [25]:
((x**2 - 1)*(x**2-4)).expand()

x**4 - 5*x**2 + 4

`begin subs_1`

In [26]:
fx = x**4 - 5*x**2 + 4
fx.subs(x, 3)

40

In [27]:
#_
fxy = (x-y)*(x+2*y)
# Eine Liste von Tupeln ersetzt mehrere Variablen
fxy.subs([(x, 1), (y, 2)])

-5

`end`

`begin subs_2`

In [28]:
z = sp.symbols('z')
fx.subs(x**2, z)

z**2 - 5*z + 4

In [29]:
#_
a, b = sp.symbols('a b')
my_term = a/b - b/a

a/b - b/a

In [30]:
my_term.subs(a/b, x)

x - b/a

`end`

`begin subs_3`

In [31]:
my_term.subs([(a/b, x), (b/a, 1/x)])

x - 1/x

`end`

# Solve

`begin solve_1`

In [32]:
x, y = sp.symbols('x, y')

In [33]:
sp.solve(5*x+4)  # skalare lineare Gleichung

[-4/5]

In [34]:
sp.solve(sp.sqrt(x) - 2*x**2)  # skalare nicht-lineare Gleichung

[0, 2**(1/3)/2]

In [35]:
sp.solve([x + 2*y + 3, 2*x + y])  # lineares Gleichungssystem

{x: 1, y: -2}

`end`

`begin solve_2`

In [36]:
# Gleichungssystem mit mehreren Lösungen
sp.solve([y - x, (x-1)**2+(y-1)**2 - 1])
print("[{x: 1 - sqrt(2)/2, y: 1 - sqrt(2)/2},\n {x: sqrt(2)/2 + 1, y: sqrt(2)/2 + 1}]") #!

[{x: 1 - sqrt(2)/2, y: 1 - sqrt(2)/2},
 {x: sqrt(2)/2 + 1, y: sqrt(2)/2 + 1}]


`end solve_2`

`begin solve_31`

In [37]:
sp.solve([2*x-4*y-2, x-2*y-1])

{x: 2*y + 1}

`end`

`begin solve_32`

In [38]:
sp.solve([2*x-4*y-2, x-2*y-1], y)

{y: x/2 - 1/2}

`end`

`begin ineq`

In [39]:
sp.solve(x**2 < x)

(0 < x) & (x < 1)

`end`

`begin solve_assumptions_1`

In [40]:
sp.solve(x**3-3*x**2+4*x-12)

[3, -2*I, 2*I]

`end`

`begin solve_assumptions_2`

In [41]:
x = sp.Symbol('x', real=True)
sp.solve(x**3-3*x**2+4*x-12)

[3]

`end`

`begin evalf`

In [42]:
fx = sp.sin(x) + sp.cos(x)
fx.subs(x, sp.pi/4)

sqrt(2)

In [43]:
# Näherung auf standardmäßig 15 Stellen
fx.subs(x, sp.pi/4).evalf()

1.41421356237310

In [44]:
# Anzahl gewünschter Stellen explizit angeben
sqrt_num = fx.subs(x, sp.pi/4).evalf(30)

1.41421356237309504880168872421

In [45]:
type(sqrt_num)

sympy.core.numbers.Float

In [46]:
float(sqrt_num)  # Umwandlung in Python-float

1.4142135623730951

`end`

In [47]:
# subs durch Schlüsselwort intern aufrufen
fx.evalf(subs={x: sp.pi/4})

1.41421356237310

`begin expand`

In [48]:
sp.expand((x+5)*(y-3)**2)

x*y**2 - 6*x*y + 9*x + 5*y**2 - 30*y + 45

In [49]:
sp.expand((x+2)*(x-1) - x*(x+1))

-2

`end`

## simplify

`begin simplify`

In [50]:
sp.simplify((x**3-6*x**2+11*x-6)/(x**2-5*x+6))

x - 1

In [51]:
sp.simplify((sp.sin(x)+sp.cos(x))**2 - sp.sin(2*x))

1

In [52]:
f = sp.exp(x**2)*sp.exp(x-x**2)
f.simplify()  # Auch als Methode aufrufbar

exp(x)

`end`

# Matrizen

`begin matrix_def`

In [53]:
x, y, a = sp.symbols('x y a')
A = sp.Matrix([[1, a], [a**2, 2]])

Matrix([
[   1, a],
[a**2, 2]])

In [54]:
B = sp.Matrix([[1, 2], [3, 4]])

Matrix([
[1, 2],
[3, 4]])

In [55]:
b = sp.Matrix([x, y])  # Abkürzung für Spaltenvektoren

Matrix([
[x],
[y]])

`end`

`begin matrix_read`

In [56]:
A.rows  # und A.cols

2

In [57]:
A[1, 0]  # [Zeile, Spalte]

a**2

`end`

`begin matrix_ops`

In [58]:
A + B

Matrix([
[       2, a + 2],
[a**2 + 3,     6]])

In [59]:
A * b  # Matrix-Multiplikation

Matrix([
[     a*y + x],
[a**2*x + 2*y]])

In [60]:
# Erinnerung: In NumPy multipliziert * elementweise

In [61]:
A.T  # transponieren

Matrix([
[1, a**2],
[a,    2]])

In [62]:
A.inv()  # invertieren

Matrix([
[    2/(2 - a**3), -a/(2 - a**3)],
[-a**2/(2 - a**3),  1/(2 - a**3)]])

In [63]:
A.subs(a, 2)  # Termoperationen funktionieren

Matrix([
[1, 2],
[4, 2]])

`end`

# Differential- und Integralrechnung

In [64]:
sp.var('x, y')

(x, y)

## Differentiation

`begin diff1`

In [65]:
sp.diff(x**2)

2*x

In [66]:
sp.diff(sp.sin(x**2)*sp.cos(x**2))

-2*x*sin(x**2)**2 + 2*x*cos(x**2)**2

In [67]:
#_
# Dritte Ableitung
fun_d3 = sp.diff(sp.sin(x**2)*sp.cos(x**2), x, 3)
print("4*x*((2*x**2*sin(x**2) - 3*cos(x**2))*sin(x**2) +\n     3*(2*x**2*sin(x**2) - cos(x**2))*sin(x**2) -\n     3*(2*x**2*cos(x**2) + sin(x**2))*cos(x**2) -\n     (2*x**2*cos(x**2) + 3*sin(x**2))*cos(x**2))") #!

4*x*((2*x**2*sin(x**2) - 3*cos(x**2))*sin(x**2) +
     3*(2*x**2*sin(x**2) - cos(x**2))*sin(x**2) -
     3*(2*x**2*cos(x**2) + sin(x**2))*cos(x**2) -
     (2*x**2*cos(x**2) + 3*sin(x**2))*cos(x**2))


In [68]:
sp.simplify(fun_d3)

-32*x**3*cos(2*x**2) - 24*x*sin(2*x**2)

In [69]:
#_
term = 1/(sp.tan(x)**2)
term.diff()  # Auch als Methode aufrufbar

(-2*tan(x)**2 - 2)/tan(x)**3

`end`

`begin diff2`

In [70]:
#!sp.diff((x+3*y)*(y-3*x))
print("ValueError:\nSince there is more than one variable in the expression, the\nvariable(s) of differentiation must be supplied to differentiate\n(x+3*y)*(y-3*x)")#!

ValueError:
Since there is more than one variable in the expression, the
variable(s) of differentiation must be supplied to differentiate
(x+3*y)*(y-3*x)


In [71]:
#_
# Bei mehreren Variablen Ableitungsrichtung explizit angeben
sp.diff((x+3*y)*(y-3*x), x)

-6*x - 8*y

In [72]:
sp.diff((x+3*y)*(y-3*x), y)

-8*x + 6*y

In [73]:
# Alternative für zweite Ableitung nach x
sp.diff((x+3*y)*(y-3*x), x, x)

-6

In [74]:
# Ableitung nach x, dann nach y
sp.diff((x+3*y)*(y-3*x), x, y)

-8

`end`

`begin jacobian`

In [75]:
x1, x2 = sp.symbols('x1 x2')
f = sp.Matrix([sp.sin(x1), x1*x2])
f.jacobian([x1, x2])  # Argument ist Liste von freien Variablen

Matrix([
[cos(x1),  0],
[     x2, x1]])

`end`

`begin def_si`

In [76]:
def si(x):
    return sp.sin(x)/x

In [77]:
si(x)

sin(x)/x

In [78]:
si(3*x+2)  # beliebige Argumente möglich

sin(3*x + 2)/(3*x + 2)

In [79]:
sp.diff(si(x))  # Ableitung der Spaltfunktion

cos(x)/x - sin(x)/x**2

`end`

`begin def_rect`

In [80]:
def rect(x):
    return sp.Piecewise((1, (-sp.S(1)/sp.S(2) <= x) & \
                            (x <= sp.S(1)/sp.S(2))), (0, True))

In [81]:
sp.simplify(2*rect(x/5))

Piecewise((2, (x >= -5/2) & (x <= 5/2)), (0, True))

`end`

## Integration

`begin integration_1`

In [82]:
x, y, z, a = sp.symbols('x y z a')

In [83]:
sp.integrate(2*x)

x**2

In [84]:
#_
# Explizite Angabe der Integrationsvariable
sp.integrate(sp.exp(-a*x), x)

Piecewise((-exp(-a*x)/a, Ne(a, 0)), (x, True))

In [85]:
#_
# Bestimmtes Integral
sp.integrate(sp.exp(-x), (x, 0, 1))

1 - exp(-1)

In [86]:
#_
# "Unendlich" wird geschrieben als "oo"
# (zwei Mal der kleine Buchstabe "o")
sp.integrate(sp.exp(-x), (x, 0, sp.oo))

1

$F(r) = (x^2, y^2, z^2)^T$ integriert über Oberfläche Einheitswürfel

In [87]:
#_
# Integral über mehrere Variablen
sp.integrate(2*x+2*y+2*z, (x, 0, 1), (y, 0, 1), (z, 0, 1))

3

`end`

In [88]:
f = sp.Symbol('f', real=True)
t = sp.Symbol('t', real=True)
T = sp.Symbol('T', real=True)
tau = sp.Symbol('tau', real=True)

tau

`begin fourier_def --input_prefix=""`

In [89]:
# Ohne "real=True" wird Integral nicht ausgewertet
# oder Fallunterscheidung komplizierter
def fourier_transform(s, t):
    # f > 0 ist streng genommen nicht sauber,
    # aber liefert lesbarere Ergebnisse
    f = sp.Symbol('f', real=True, positive=True)
    return sp.integrate(s*sp.exp(-2*sp.pi*sp.I*f*t),
                        (t, -sp.oo, sp.oo))

`end`

!! In der folgenden Zelle ist ein Tippfehler im Buch:

Statt `fourier_transform(rect(t)).simplify()` muss es `fourier_transform(rect(t), t).simplify()` heißen (2. Argument hat gefehlt).

`begin fourier_call`

In [90]:
t = sp.Symbol('t', real=True)
fourier_transform(rect(t), t).simplify()

sin(pi*f)/(pi*f)

In [91]:
# "Heaviside" ist Einheitssprung
#!fourier_transform(sp.exp(-t)*sp.Heaviside(t), t)
fourier_transform(sp.exp(-t)*sp.Heaviside(t), t).simplify() #!

1/(2*I*pi*f + 1)

`end`

In [92]:
sp.simplify(fourier_transform(si(sp.pi*t), t))

Piecewise((Piecewise((0, f**2 > 1/4), (1, True)), Ne(1/(4*f**2), 1)), (Integral(exp(-2*I*pi*f*t)*sin(pi*t)/t, (t, -oo, oo))/pi, True))

`begin fold`

In [93]:
tau = sp.symbols('tau')
# Faltung zweier Rechtecksignale
sp.integrate(rect(tau)*rect(t-tau), (tau, -sp.oo, sp.oo))

-Max(-1/2, t - 1/2) + Max(-1/2, t - 1/2, Min(1/2, t + 1/2))

`end fold`

# Lambdify

`begin lambdify_1`

In [94]:
# Beispielfunktion: Taylor-Polynom von exp(-x)
# sp.series macht Reihenentwicklung
sp.series(sp.exp(-x))

1 - x + x**2/2 - x**3/6 + x**4/24 - x**5/120 + O(x**6)

In [95]:
# removeO entfernt Landau-Symbol O
f_symb = sp.series(sp.exp(-x)).removeO()

-x**5/120 + x**4/24 - x**3/6 + x**2/2 - x + 1

In [96]:
f_symb.subs(x, 1).evalf()

0.366666666666667

In [97]:
#_
f_num = sp.lambdify(x, f_symb)

<function _lambdifygenerated(x)>

In [98]:
f_num(1)

0.3666666666666667

In [99]:
#_
import numpy as np
xs = np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [100]:
f_num(xs)  # Viele Auswertungen auf einmal

array([  1.        ,   0.60651042,   0.36666667,   0.21015625,
         0.06666667,  -0.16536458,  -0.65      ,  -1.64505208,
        -3.53333333,  -6.85390625, -12.33333333])

`end`

`begin lambdify_mat_1`

In [101]:
x1, x2 = sp.symbols('x1, x2')
f_symb = sp.Matrix([[x1**2, sp.sin(x1)*sp.sin(x2)],
                    [sp.cos(x2), x2**2]])

Matrix([
[  x1**2, sin(x1)*sin(x2)],
[cos(x2),           x2**2]])

In [102]:
# Rückgabewert ist Funktionsobjekt
f_num = sp.lambdify([x1, x2], f_symb)

<function _lambdifygenerated(x1, x2)>

In [103]:
f_num(1, 2)

array([[ 1.        ,  0.7651474 ],
       [-0.41614684,  4.        ]])

`end`

`begin lambdify_mat_2`

In [104]:
def f_vec_input(x):
    return f_num(*x)
x_vec = np.array([1, 2])
f_vec_input(x_vec)

array([[ 1.        ,  0.7651474 ],
       [-0.41614684,  4.        ]])

`end`