# Echt Klasse: Fortgeschrittene Programmierung


Dieses Jupyter-Notebook enthält den Quelltext für Kapitel 14 »Echt Klasse: Fortgeschrittene Programmierung« im Buch [Python für Ingenieure für Dummies](https://python-fuer-ingenieure.de/).

### Objektorientierung

---
In diesem Notebook muss ein bisschen gezaubert werden, weil einige Schnipsel fürs Buch statt des üblichen `>>` einen leeren String als *Input-Präfix* haben sollen und außerdem zur Abkürzung `...` enthalten sollen. Grund: Die Klasse Vector wird im Buch mehrfach erweitert, aber Wiederhohlungen sollen vermieden werden. Lösung: Schnipsel-Zellen, die nur `#!`-Kommentare enthalten. Der eigentliche Code steht dann außerhalb von `begin ...` und `end`.

In [1]:
class Vector:
    def __init__(self, *args):
        self.values = args

`begin vec_def --input_prefix ""`

In [2]:
#!class Vector:
#!    def __init__(self, *args):
#!        self.values = args

`end`

`begin vec_new`

In [3]:
x = Vector(1, 5)  # Anlegen der Instanz
x

In [4]:
x.values  # Lesen der Instanzvariable

(1, 5)

`end`

In [5]:
class Vector:
    def __init__(self, *args):
        self.values = args
        
    def __repr__(self):
        return "Vector" + str(self.values)
        
    def __str__(self):
        return repr(se2lf)
    
    def add(self, other):
        # Beide Vektoren müssen die gleiche Dimension haben
        assert len(self.values) == len(other.values)
        result = []
        # zip(a, b) gibt pro Iteration immer ein zusammengehöriges
        # Paar von Werten aus beiden Listen zurück
        for val1, val2 in zip(self.values, other.values):
            result.append(val1 + val2)
        return Vector(*result)
    
    def scale(self, scalar):
        result = []
        for val in self.values:
            result.append(scalar * val)
        return Vector(*result)
    
    def dot(self, other):
        assert len(self.values) == len(other.values)
        result = 0
        for val1, val2 in zip(self.values, other.values):
            result += val1 * val2
        return result
    
    def __add__(self, other):
        return self.add(other)
    
    def __mul__(self, other):
        if isinstance(other, Vector):
            return self.dot(other)
        else:
            return self.scale(other)

`begin vec_str --input_prefix ""`

In [6]:
#!class Vector:
#!    ...
#!    def __repr__(self):
#!        return "Vector" + str(self.values)
        
#!    def __str__(self):
#!        return repr(self)

`end`

`begin vec_methods --input_prefix ""`

In [7]:
#!class Vector:
#!    ...
#!    def add(self, other):
#!        # Beide Vektoren müssen die gleiche Dimension haben
#!        assert len(self.values) == len(other.values)
#!        result = []
#!        # zip(a, b) gibt pro Iteration immer ein zusammengehöriges
#!        # Paar von Werten aus beiden Listen zurück
#!        for val1, val2 in zip(self.values, other.values):
#!            result.append(val1 + val2)
#!        return Vector(*result)
#!    
#!    def scale(self, scalar):
#!        result = []
#!        for val in self.values:
#!            result.append(scalar * val)
#!        return Vector(*result)
#!    
#!    def dot(self, other):
#!        assert len(self.values) == len(other.values)
#!        result = 0
#!        for val1, val2 in zip(self.values, other.values):
#!            result += val1 * val2
#!        return result

`end`

`begin vec_overloading --input_prefix ""`

In [8]:
#!class Vector:
#!    ...
#!    def __add__(self, other):
#!        return self.add(other)
#!    
#!    def __mul__(self, other):
#!        if isinstance(other, Vector):
#!            return self.dot(other)
#!        else:
#!            return self.scale(other)

`end`

`begin vec_test`

In [9]:
Vector(1, 2).add(Vector(3, 4))

Vector(4, 6)

In [10]:
Vector(1, 2).scale(5.5)

Vector(5.5, 11.0)

In [11]:
Vector(1, 2).dot(Vector(3, 4))

11

`end`

Eine Allesfresserfunktion....

`begin omnivore --input_prefix ""`

In [12]:
def omnivore(*args, **kwargs):
    print("args=", args)
    print("kwargs=", kwargs)

`end`

`begin omnivore_call`

In [13]:
omnivore("one", 2, three="four", five=6)

args= ('one', 2)
kwargs= {'three': 'four', 'five': 6}


`end`

`begin add_user --input_prefix ""`

In [14]:
def add_user(name, country, address=None, birthday=None, phone=None):
    for string, val in zip(["Name", "Country", "Address", "Birthday", "Phone"],
                           [name, country, address, birthday, phone]):
        print(string + ": " + str(val))

`end`

`begin add_user_call`

In [15]:
required = ["Peter Pan", "Nimmerland"]
optional = {"birthday": "1902-11-01"}
add_user(*required, **optional)

Name: Peter Pan
Country: Nimmerland
Address: None
Birthday: 1902-11-01
Phone: None


`end`

`begin vec_overloading_test`

In [16]:
Vector(1, 1) + Vector(2, 3) * 4

Vector(9, 13)

`end`

`begin vec3d_def --input_prefix ""`

In [17]:
class Vector3D(Vector):    
    # 3D Vektor akzeptiert nur drei Komponenten
    def __init__(self, x, y, z):
        # Konstruktor der Elternklasse aufrufen
        super().__init__(x, y, z)
        
    def x(self):
        # Zugriff auf Attribute in Elternklasse
        return self.values[0]
    def y(self):
        return self.values[1]
    def z(self):
        return self.values[2]
    
    def cross(self, other):
        assert isinstance(other, Vector3D)
        return Vector3D(self.y() * other.z() - self.z() * other.y(),
                        self.z() * other.x() - self.x() * other.z(),
                        self.x() * other.y() - self.y() * other.x())

`end`

`begin vec3d_test`

In [18]:
# Kreuzprodukt von Einheitsvektoren in x- und y-Richtung
# ergibt Einheitsvektor in z-Richtung
Vector3D(1, 0, 0).cross(Vector3D(0, 1, 0))

Vector(0, 0, 1)

`end`

# Exceptions

`begin try_dice --input_prefix "" --output_prefix ">> "`

In [19]:
import random

#!nr_dice = None
# Frage Nutzer so lange, bis eine gültige Eingabe kommt
#!while nr_dice is None:
#!    print("Wie viele Würfel möchten Sie werfen?")
#!    try:
        # int(...) kann schiefgehen, deswegen sicher in
        # try...except einpacken
#!        nr_dice = int(input())
#!    except ValueError:
#!        print("Ungültige Eingabe. Versuchen Sie es erneut.")

# Berechne Würfelergebnisse
#!dice_results = [random.randint(1, 6) for i in range(nr_dice)]
#!dice_sum = sum(dice_results)
#!print("Ergebnisse:",
#!      ", ".join(str(result) for result in dice_results))
#!print("Summe:", dice_sum)
print("Wie viele Würfel möchten Sie werfen?\n rosinenbrötchen\nUngültige Eingabe. Versuchen Sie es erneut.\nWie viele Würfel möchten Sie werfen?\n 12\nErgebnisse: 6, 2, 1, 3, 4, 3, 1, 1, 2, 4, 6, 5\nSumme: 38") #!

Wie viele Würfel möchten Sie werfen?
 rosinenbrötchen
Ungültige Eingabe. Versuchen Sie es erneut.
Wie viele Würfel möchten Sie werfen?
 12
Ergebnisse: 6, 2, 1, 3, 4, 3, 1, 1, 2, 4, 6, 5
Summe: 38


`end`

`begin raise_dice --input_prefix ""`

In [20]:
class NotAnIntError(Exception):
    def __init__(self, value):
        self.value = value
class InvalidAmountError(Exception):
    pass  # Keine Anpassungen nötig

def str_to_amount(amount_str):
    try:
        amount = int(amount_str)
    except ValueError:
        raise NotAnIntError(amount_str)
    if amount < 1:
        raise InvalidAmountError(Exception)
    return amount

`end`

`begin dice_new_loop --input_prefix "" --output_prefix ">> "`

In [21]:
#!import random

#!nr_dice = None
#!while nr_dice is None:
#!    print("Wie viele Würfel möchten Sie werfen?")
#!    try:
#!        nr_dice = str_to_amount(input())
#!    except NotAnIntError as e:
#!        # Exception-Objekt in Variable e speichern
#!        print(f"Ungültige Eingabe '{e.value}'. Ganzzahl \
#!eingeben!")
#!    except InvalidAmountError:
#!        print("Anzahl der Würfe muss mindestens eins sein.")

#!dice_results = [random.randint(1, 6) for i in range(nr_dice)]
#!dice_sum = sum(dice_results)
#!print("Ergebnisse: " + \
#!      ", ".join(str(result) for result in dice_results))
#!print("Summe: " + str(dice_sum))
print("Wie viele Würfel möchten Sie werfen?\n sauerbraten\nUngültige Eingabe 'sauerbraten'. Ganzzahl eingeben!\nWie viele Würfel möchten Sie werfen?\n -8\nAnzahl der Würfe muss mindestens eins sein.\nWie viele Würfel möchten Sie werfen?\n 6\nErgebnisse: 6, 1, 5, 5, 6, 3\nSumme: 26")  #!

Wie viele Würfel möchten Sie werfen?
 sauerbraten
Ungültige Eingabe 'sauerbraten'. Ganzzahl eingeben!
Wie viele Würfel möchten Sie werfen?
 -8
Anzahl der Würfe muss mindestens eins sein.
Wie viele Würfel möchten Sie werfen?
 6
Ergebnisse: 6, 1, 5, 5, 6, 3
Summe: 26


`end`

# List Comprehensions

`begin lc_1_classic`

In [22]:
numbers = [0, 0, 1, 4, 11, 24, 50, 80, 154, 220]
numbers_str = []
for n in numbers:
    numbers_str.append(str(n))
print(numbers_str)

['0', '0', '1', '4', '11', '24', '50', '80', '154', '220']


`end`

`begin lc_1`

In [23]:
# Für jede Zahl n aus numbers werte die Funktion str(n) aus
numbers_str = [str(n) for n in numbers]
print(numbers_str) #!

['0', '0', '1', '4', '11', '24', '50', '80', '154', '220']


In [24]:
# Strings in Liste mit Trennzeichen verbinden
" | ".join(numbers_str)

'0 | 0 | 1 | 4 | 11 | 24 | 50 | 80 | 154 | 220'

`end`

`begin lc_2`

In [25]:
#![n for n in range(1, 100) if "4" not in str(n)]
allowed_room_numbers = [n for n in range(1, 20) if "4" not in str(n)] #!
print(allowed_room_numbers)  #!

[1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19]


`end`

`begin lc_3`

In [26]:
movies = [("Citizen Kane", "1941-09-04"), ("The Godfather", "1972-03-11"), ("Rear Window", "1954-09-01"),
 ("Casablanca", "1943-01-23"), ("Boyhood", "2014-07-11"), ("Three Colors: Red", "1994-11-23"),
 ("Vertigo", "1958-05-28"), ("Notorious", "1946-09-06"), ("Singin' in the Rain", "1952-04-11"),
 ("City Lights", "1931-03-07")]

In [27]:
import datetime
# Name (in Großbuchstaben) aller Filme, die an einem Samstag Premiere hatten
[title.upper() for title, date_str in movies if datetime.date.fromisoformat(date_str).weekday() == 5]

['THE GODFATHER', 'CASABLANCA', 'CITY LIGHTS']

`end`

`begin lc_3_alt`

In [28]:
from datetime import date
#!current_date = date.today()   # 12.02.2021
current_date = date(2021, 2, 12) #!
devices = [("Supervolt All-In-One", 8, "2019-05-21"),
 ("Technotron 84b", 2, "2020-04-25"),
 ("eSPACE IOX", 3, "2018-12-10"),
 ("annoScope Series S", 1, "2020-04-16")]
[f"{name}: {amount} Geräte"
 for name, amount, last_inspection in devices
 if (current_date -
     date.fromisoformat(last_inspection)).days > 365]

['Supervolt All-In-One: 8 Geräte', 'eSPACE IOX: 3 Geräte']

`end`

# Funktionen-Tricks

`begin fun_type`

In [29]:
def empty_function():
    pass
#_
type(empty_function)

function

`end`

`begin def_sys_rhs`

In [30]:
from scipy.integrate import solve_ivp
import numpy as np
#_
def sys_rhs(t, x):
    return np.array([x[1], -x[0]])
#_
# Übergib sys_rhs als Objekt an Funktion solve_ivp
# Argumente: DGL-Funktion, Start-/Endzeit, Startwert
res = solve_ivp(sys_rhs, (0, 10), np.array([1, 1]))
res.y[:,-1]  # x nach 10 s

array([-1.38380744, -0.29095011])

`end`

`begin fun_vs_call`

In [31]:
sys_rhs  # Funktionsobjekt

<function __main__.sys_rhs(t, x)>

In [32]:
sys_rhs(0, [1, 1])  # Funktionswert

array([ 1, -1])

`end`

`begin rhs_lambda`

In [33]:
res = solve_ivp(lambda t, x: np.array([x[1], -x[0]]),
                (0, 10), np.array([1, 1]))

`end`

`begin matrix_to_fun`

In [34]:
# Funktion, die aus einer Systemmatrix eine Funktion mit
# Argumenten (t, x) generiert
def matrix_to_fun(A):
    # Definiere Systemfunktion auf Basis der Matrix
    def _sys_rhs(t, x):
        return A @ x
    
    return _sys_rhs # Gib Funktionsobjekt zurück
#_
# DGL-System als Matrix
A = np.array([[0, 1], [-1, 0]])
# Konvertiere Matrix in aufrufbare Funktion
sys_rhs = matrix_to_fun(A)
# Integration der DGL genau wie vorher
res = solve_ivp(sys_rhs, (0, 10), np.array([1, 1]))
res.y[:,-1]  # x nach 10 s

array([-1.38380744, -0.29095011])

`end`